apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-ldap
  namespace: ingress-nginx
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: nginx-ldap
  namespace: ingress-nginx
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
    resourceNames:
      - "nginx-ldap"
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: nginx-ldap
  namespace: ingress-nginx
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nginx-ldap
subjects:
  - kind: ServiceAccount
    name: nginx-ldap
---
kind: Service
apiVersion: v1
metadata:
  name: nginx-ldap
  namespace: ingress-nginx
spec:
  type: ClusterIP
  ports:
    - name: nginx-ldap
      port: 5555
      protocol: TCP
      targetPort: 5555
  selector:
    app: nginx-ldap
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx-ldap
  namespace: ingress-nginx
  labels:
    app: nginx-ldap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-ldap
  template:
    metadata:
      labels:
        app: nginx-ldap
    spec:
      serviceAccountName: nginx-ldap
      containers:
        - image: docker.io/tpimenta/nginx-ldap:v1.0.6
          name: nginx-ldap
          command:
            - "/usr/local/bin/nginx-ldap"
            - "--config"
            - "/etc/nginx-ldap/config.yaml"
          ports:
            - name: http
              containerPort: 5555
          volumeMounts:
            - name: config
              mountPath: /etc/nginx-ldap
          resources:
            limits:
              cpu: 50m
              memory: 20Mi
            requests:
              cpu: 10m
              memory: 5Mi
      volumes:
        - name: config
          secret:
            secretName: nginx-ldap
            items:
              - key: config.yaml
                path: config.yaml
